version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/pythonservice
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:16
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  celery:
    build: .
    command: celery -A pythonservice worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
